import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

/**
 * Guards for the generated Colab notebook.
 *
 * The notebook is regenerated by `scripts/build-colab-notebook.ts`, so these
 * assert the properties that were paid for in debugging on a live free T4 and
 * must not silently regress on the next regeneration.
 */

const notebook = JSON.parse(
  fs.readFileSync(
    path.resolve(__dirname, "..", "notebooks/amedspor_ltx_i2v.ipynb"),
    "utf8",
  ),
) as { cells: Array<{ cell_type: string; source: string[] }>; metadata: Record<string, unknown> };

const codeCells = notebook.cells
  .filter((c) => c.cell_type === "code")
  .map((c) => c.source.join(""));
const allCode = codeCells.join("\n");

describe("notebook structure", () => {
  it("declares a GPU accelerator", () => {
    expect(notebook.metadata.accelerator).toBe("GPU");
  });

  it("has code cells", () => {
    expect(codeCells.length).toBeGreaterThan(8);
  });
});

describe("host-RAM staging (why loading used to hang)", () => {
  it("loads the text encoder in 8-bit straight to the GPU", () => {
    // Loading T5-XXL in bf16 through host RAM is what wedged a free Colab VM.
    expect(allCode).toContain("load_in_8bit=True");
    expect(allCode).toContain("device_map='auto'");
  });

  it("skips transformer and VAE while encoding the prompt", () => {
    expect(allCode).toContain("transformer=None");
    expect(allCode).toContain("vae=None");
  });

  it("frees the encoder before loading the transformer", () => {
    expect(allCode.indexOf("del shell, text_encoder")).toBeLessThan(
      allCode.indexOf("text_encoder=None,\n    tokenizer=None,"),
    );
  });

  it("generates from precomputed embeddings, never a raw prompt", () => {
    const generation = codeCells.find((c) => c.includes("result = pipe("))!;
    expect(generation).toContain("prompt_embeds=PROMPT_EMBEDS");
    expect(generation).not.toContain("prompt=PROMPT,");
  });
});

describe("Pillow floor (the _Ink ImportError)", () => {
  it("pins pillow to a version that exports PIL._typing._Ink", () => {
    // Colab ships Pillow 11.x; diffusers' LTX pipeline imports _Ink, which
    // only exists from 12.0. Verified empirically: absent in 10.4/11.0/11.3.
    expect(allCode).toContain("pillow>=12.0.0");
  });

  it("detects a stale preloaded PIL and restarts rather than failing", () => {
    // pip can upgrade files on disk while the kernel keeps the old module in
    // sys.modules — which is precisely how the _Ink error appeared.
    expect(allCode).toContain("PIL.__version__ != disk_version");
    expect(allCode).toContain("os.kill(os.getpid(), 9)");
  });

  it("probes the on-disk install in a clean interpreter", () => {
    // Distinguishes "install is broken" from "this kernel is stale".
    expect(allCode).toContain("capture_output=True");
    expect(allCode).toContain("from diffusers import LTXImageToVideoPipeline");
  });
});

describe("output integrity", () => {
  it("keeps the frame-delta assertion that rejects frozen output", () => {
    expect(allCode).toContain("mean_delta > 0.35");
    expect(allCode).toContain("np.diff");
  });

  it("passes max_sequence_length explicitly rather than truncating at 128", () => {
    expect(allCode).toContain("max_sequence_length=MAX_SEQ");
  });

  it("never synthesises motion from a still", () => {
    for (const forbidden of ["zoompan", "Ken Burns", "loop=1", "-loop 1"]) {
      expect(allCode.toLowerCase()).not.toContain(forbidden.toLowerCase());
    }
  });
});

describe("deferred decode (why cell 7 used to hang after 30/30)", () => {
  it("returns latents from the denoise call instead of decoding inside it", () => {
    expect(allCode).toContain("output_type='latent'");
  });

  it("checkpoints the latents so decode can be retried without re-denoising", () => {
    expect(allCode).toContain("/content/latents_shot2.pt");
    expect(allCode).toContain("torch.save(");
  });

  it("releases the transformer before decoding", () => {
    // Holding ~4 GiB of transformer on a 16 GiB card starves the decode.
    expect(allCode).toContain("pipe.transformer = None");
    expect(allCode.indexOf("pipe.transformer = None")).toBeLessThan(
      allCode.indexOf("vae.decode("),
    );
  });

  it("decodes in fp16, not bf16", () => {
    // The T4 is Turing (sm_75) with no native bf16 path, so the VAE's 3D
    // convolutions fall back to a very slow kernel and look like a hang.
    expect(allCode).toContain("vae.to('cuda', dtype=torch.float16)");
  });

  it("brackets the decode with logging so a stall is locatable", () => {
    expect(allCode).toContain("VAE DECODE START");
    expect(allCode).toContain("VAE DECODE DONE");
  });

  it("still produces frames_out and exports the MP4", () => {
    expect(allCode).toContain("frames_out = pipe.video_processor.postprocess_video");
    expect(allCode).toContain("export_to_video(frames_out");
  });
});

describe("generation geometry", () => {
  it("uses a size the LTX VAE can actually accept", () => {
    // A profile-resolution bug once emitted 720x1280 here, which fails the
    // notebook's own divisible-by-32 assertion before anything renders.
    const match = allCode.match(/W, H = (\d+), (\d+)/);
    expect(match).not.toBeNull();
    const [w, h] = [Number(match![1]), Number(match![2])];
    expect(w % 32).toBe(0);
    expect(h % 32).toBe(0);
    expect(allCode).toContain(`WIDTH, HEIGHT = ${w}, ${h}`);
  });

  it("keeps frame count on the 8n+1 temporal stride", () => {
    const match = allCode.match(/NUM_FRAMES = (\d+)/);
    expect((Number(match![1]) - 1) % 8).toBe(0);
  });
});
