import { z } from "zod";
import { DirectorBrief } from "./brief";
import {
  AspectRatio,
  BackgroundActivity,
  CameraAngle,
  CameraDevice,
  CameraHeight,
  CameraMove,
  ColorGrade,
  DeliveryFormat,
  DepthOfField,
  FocusBehavior,
  LightingStyle,
  Mood,
  RealismLevel,
  ReferenceRole,
  ReferenceUsage,
  ShotPurpose,
  ShotSize,
  SocialArchetype,
  Strictness,
  SubjectKind,
  TimeOfDay,
  VisualStyle,
} from "./vocab";

export const SPEC_VERSION = "1.0.0" as const;

// --------------------------------------------------------------------------
// Camera
// --------------------------------------------------------------------------

/**
 * A fully resolved camera instruction for one shot.
 *
 * These are numbers and enums, not prose. Prose is generated later by the
 * provider prompt adapter, so a model that prefers "dolly in slowly" and a
 * model that prefers "camera: push_in, speed 0.3" can both be served from the
 * same directive.
 */
export const CameraDirective = z.object({
  presetId: z.string().min(1),
  presetLabel: z.string().min(1),
  device: CameraDevice,
  shotSize: ShotSize,
  angle: CameraAngle,
  height: CameraHeight,
  /** Dominant movement for the shot. */
  primaryMove: CameraMove,
  /** Optional layered movement (e.g. push_in + handheld_drift). */
  secondaryMove: CameraMove.nullable().default(null),
  /** 0 = imperceptible, 1 = dramatic. Kept low by default on purpose. */
  moveIntensity: z.number().min(0).max(1),
  /** How fast the move completes across the shot. 0 = glacial, 1 = fast. */
  moveSpeed: z.number().min(0).max(1),
  /** 1 = locked off tripod, 0 = deliberately loose handheld. */
  stability: z.number().min(0).max(1),
  /** Sub-pixel breathing that sells "a human is holding this". */
  microJitter: z.number().min(0).max(1),
  /** Approximate full-frame-equivalent focal length. Drives perspective prose. */
  focalLengthMm: z.number().min(8).max(200),
  depthOfField: DepthOfField,
  focusBehavior: FocusBehavior,
  /** Metres from lens to hero subject. Drives framing and DoF language. */
  subjectDistanceM: z.number().min(0.05).max(30),
  /** How much foreground/background separation the move should reveal. */
  parallax: z.number().min(0).max(1),
  framingNotes: z.string().max(400).default(""),
  /** Why the camera director chose this. Shown in the plan inspector. */
  rationale: z.string().max(400).default(""),
});
export type CameraDirective = z.infer<typeof CameraDirective>;

// --------------------------------------------------------------------------
// Realism
// --------------------------------------------------------------------------

export const REALISM_DOMAINS = [
  "human_anatomy",
  "hands",
  "facial_identity",
  "food_texture",
  "liquid_physics",
  "product_geometry",
  "branding_legibility",
  "material_texture",
  "lighting_physics",
  "camera_optics",
  "motion_physics",
  "temporal_stability",
  "scene_coherence",
] as const;
export const RealismDomain = z.enum(REALISM_DOMAINS);
export type RealismDomain = z.infer<typeof RealismDomain>;

export const RealismDirective = z.object({
  level: RealismLevel,
  /** Per-domain strictness. `off` domains are never mentioned in prompts. */
  emphasis: z.record(RealismDomain, Strictness),
  /** Affirmative realism statements, already ordered by importance. */
  positives: z.array(z.string().min(1)),
  /** Negative constraints — what the model must avoid. */
  negatives: z.array(z.string().min(1)),
  /** Ids of the catalogue rules that fired. Useful for debugging the engine. */
  appliedRuleIds: z.array(z.string()),
});
export type RealismDirective = z.infer<typeof RealismDirective>;

// --------------------------------------------------------------------------
// Motion
// --------------------------------------------------------------------------

export const SUBJECT_MOTION = ["none", "micro", "natural", "pronounced"] as const;
export const SubjectMotion = z.enum(SUBJECT_MOTION);
export type SubjectMotion = z.infer<typeof SubjectMotion>;

export const MOTION_BLUR = ["none", "subtle", "natural", "pronounced"] as const;
export const MotionBlur = z.enum(MOTION_BLUR);
export type MotionBlur = z.infer<typeof MotionBlur>;

export const MotionDirective = z.object({
  subjectMotion: SubjectMotion,
  environmentMotion: BackgroundActivity,
  motionBlur: MotionBlur,
  /** Concrete physical behaviours the shot needs, e.g. "condensation_beading". */
  physicsTags: z.array(z.string().min(1)).default([]),
  /** Prose describing the movement, generated by the motion planner. */
  notes: z.string().max(400).default(""),
});
export type MotionDirective = z.infer<typeof MotionDirective>;

// --------------------------------------------------------------------------
// References
// --------------------------------------------------------------------------

export const ReferenceDirective = z.object({
  referenceId: z.string().min(1),
  /** Original filename — helpful in the UI. */
  label: z.string().default(""),
  role: ReferenceRole,
  usage: ReferenceUsage,
  adherence: Strictness,
  /** Normalised conditioning weight, 0..1. Adapters map this to model scales. */
  weight: z.number().min(0).max(1),
  /** `null` = applies to every shot. */
  shotIds: z.array(z.string()).nullable().default(null),
  /** What specifically must be preserved from this image. */
  preserve: z.array(z.string().min(1)).default([]),
  /**
   * Model-facing description of the image, used when no conditioning hook
   * exists. Deliberately separate from `notes`: notes explain provider
   * limitations to the operator, and that plumbing must never reach a prompt.
   */
  promptDescription: z.string().default(""),
  notes: z.string().max(400).default(""),
});
export type ReferenceDirective = z.infer<typeof ReferenceDirective>;

// --------------------------------------------------------------------------
// Consistency
// --------------------------------------------------------------------------

export const ConsistencyEntity = z.object({
  key: z.string().min(1),
  kind: SubjectKind,
  label: z.string().min(1),
  /** Attributes that must not drift between frames or shots. */
  lockedAttributes: z.array(z.string().min(1)),
  adherence: Strictness,
  /** Reference ids that anchor this entity's identity, if any. */
  anchorReferenceIds: z.array(z.string()).default([]),
});
export type ConsistencyEntity = z.infer<typeof ConsistencyEntity>;

export const SEED_POLICIES = ["shared", "per_shot", "random"] as const;
export const SeedPolicy = z.enum(SEED_POLICIES);
export type SeedPolicy = z.infer<typeof SeedPolicy>;

export const ConsistencyContract = z.object({
  /** Global dial exposed in Advanced as "consistency strength". */
  strength: z.number().min(0).max(1),
  entities: z.array(ConsistencyEntity),
  crossShot: z.object({
    lighting: Strictness,
    colorGrade: Strictness,
    wardrobe: Strictness,
    environmentLayout: Strictness,
    cameraLanguage: Strictness,
    propContinuity: Strictness,
  }),
  seedPolicy: SeedPolicy,
  baseSeed: z.number().int().min(0),
  /** Human-readable continuity statements injected into every shot prompt. */
  continuityNotes: z.array(z.string().min(1)).default([]),
});
export type ConsistencyContract = z.infer<typeof ConsistencyContract>;

// --------------------------------------------------------------------------
// Shots
// --------------------------------------------------------------------------

export const TRANSITIONS = ["cut", "dissolve", "match_cut", "whip", "fade_from_black", "fade_to_black"] as const;
export const Transition = z.enum(TRANSITIONS);
export type Transition = z.infer<typeof Transition>;

export const Shot = z.object({
  id: z.string().min(1),
  index: z.number().int().min(0),
  purpose: ShotPurpose,
  title: z.string().min(1).max(120),
  /** One concrete sentence of on-screen action. */
  action: z.string().min(1).max(400),
  featuredSubjectKeys: z.array(z.string()).default([]),
  durationSec: z.number().min(1).max(20),
  camera: CameraDirective,
  motion: MotionDirective,
  /** Per-shot resolved realism (may differ from the global default). */
  realism: RealismDirective,
  /** Reference ids that this specific shot must honour. */
  referenceIds: z.array(z.string()).default([]),
  transitionIn: Transition,
  seed: z.number().int().min(0),
});
export type Shot = z.infer<typeof Shot>;

// --------------------------------------------------------------------------
// Delivery
// --------------------------------------------------------------------------

export const DeliverySpec = z.object({
  format: DeliveryFormat,
  aspectRatio: AspectRatio,
  /** What the video model is asked to render (kept modest — GPUs are finite). */
  generation: z.object({
    width: z.number().int().min(64),
    height: z.number().int().min(64),
    fps: z.number().int().min(8).max(60),
  }),
  /** What the composer exports (upscaled/interpolated as needed). */
  export: z.object({
    width: z.number().int().min(64),
    height: z.number().int().min(64),
    fps: z.number().int().min(8).max(60),
  }),
  totalDurationSec: z.number().min(1),
});
export type DeliverySpec = z.infer<typeof DeliverySpec>;

// --------------------------------------------------------------------------
// Scene
// --------------------------------------------------------------------------

export const SceneSubject = z.object({
  key: z.string().min(1),
  kind: SubjectKind,
  label: z.string().min(1),
  description: z.string().min(1),
  hero: z.boolean(),
  identityNotes: z.array(z.string()).default([]),
});
export type SceneSubject = z.infer<typeof SceneSubject>;

export const SceneSpec = z.object({
  environment: z.object({
    setting: z.string().min(1),
    timeOfDay: TimeOfDay,
    lighting: LightingStyle,
    backgroundActivity: BackgroundActivity,
    atmosphereNotes: z.array(z.string()).default([]),
  }),
  subjects: z.array(SceneSubject).min(1),
});
export type SceneSpec = z.infer<typeof SceneSpec>;

// --------------------------------------------------------------------------
// Quality / provider / post
// --------------------------------------------------------------------------

export const QualityTargets = z.object({
  /** Below this overall score the pipeline attempts a repair pass. */
  minOverall: z.number().min(0).max(1),
  minTemporalConsistency: z.number().min(0).max(1),
  minSubjectConsistency: z.number().min(0).max(1),
  /** How many repair attempts a single shot may consume. */
  maxRepairAttempts: z.number().int().min(0).max(5),
});
export type QualityTargets = z.infer<typeof QualityTargets>;

export const ProviderPreferences = z.object({
  providerId: z.string().min(1),
  /** Free-form, provider-scoped. Never read outside the adapter. */
  options: z.record(z.string(), z.unknown()).default({}),
});
export type ProviderPreferences = z.infer<typeof ProviderPreferences>;

export const PostProduction = z.object({
  music: z.object({
    enabled: z.boolean(),
    /** Descriptive brief for a future music provider; not used by ffmpeg. */
    brief: z.string().default(""),
    trackPath: z.string().nullable().default(null),
    duckUnderVoice: z.boolean().default(false),
  }),
  captions: z.object({
    enabled: z.boolean(),
    lines: z.array(z.object({ text: z.string(), atSec: z.number().min(0), holdSec: z.number().min(0.3) })).default([]),
  }),
  branding: z.object({
    logoReferenceId: z.string().nullable().default(null),
    placement: z.enum(["none", "bottom_center", "top_left", "bottom_right"]).default("none"),
    lastFrameHold: z.boolean().default(false),
  }),
});
export type PostProduction = z.infer<typeof PostProduction>;

export const DirectorMeta = z.object({
  engine: z.enum(["llm", "heuristic"]),
  model: z.string().nullable().default(null),
  fallbackUsed: z.boolean().default(false),
  warnings: z.array(z.string()).default([]),
  elapsedMs: z.number().min(0).default(0),
});
export type DirectorMeta = z.infer<typeof DirectorMeta>;

// --------------------------------------------------------------------------
// The spec
// --------------------------------------------------------------------------

/**
 * VideoGenerationSpec — the normalised internal representation of a video.
 *
 * Every downstream system (prompt compiler, provider adapters, quality control,
 * composer) reads this and nothing else. Raw user text appears exactly once,
 * in `source.prompt`, and is never re-parsed.
 */
export const VideoGenerationSpec = z.object({
  specVersion: z.literal(SPEC_VERSION),
  id: z.string().min(1),
  projectId: z.string().min(1),
  createdAt: z.string().min(1),

  source: z.object({
    prompt: z.string(),
    language: z.string(),
    brandProfileId: z.string().nullable().default(null),
  }),

  creative: z.object({
    logline: z.string().min(1),
    visualStyle: VisualStyle,
    colorGrade: ColorGrade,
    mood: Mood,
    socialArchetype: SocialArchetype,
    aestheticTags: z.array(z.string()).default([]),
  }),

  delivery: DeliverySpec,
  scene: SceneSpec,
  realism: RealismDirective,
  consistency: ConsistencyContract,
  references: z.array(ReferenceDirective).default([]),
  shots: z.array(Shot).min(1),
  quality: QualityTargets,
  provider: ProviderPreferences,
  post: PostProduction,

  /** Provenance of the brief that produced this spec. */
  brief: DirectorBrief,
  directorMeta: DirectorMeta,
});
export type VideoGenerationSpec = z.infer<typeof VideoGenerationSpec>;

/** Convenience: the hero subject, which most engines special-case. */
export function heroSubject(spec: VideoGenerationSpec): SceneSubject {
  return spec.scene.subjects.find((s) => s.hero) ?? spec.scene.subjects[0];
}

export function shotById(spec: VideoGenerationSpec, shotId: string): Shot | undefined {
  return spec.shots.find((s) => s.id === shotId);
}

/** References that apply to a given shot (global ones included). */
export function referencesForShot(spec: VideoGenerationSpec, shotId: string): ReferenceDirective[] {
  return spec.references.filter((r) => r.shotIds === null || r.shotIds.includes(shotId));
}
